In [105]:
import numpy as np
import pandas as pd

In [106]:
x = np.array([[242, 273], [244, 286], [244, 286]])

In [108]:
x

array([[242, 273],
       [244, 286],
       [244, 286]])

In [109]:
x.shape

(3, 2)

In [110]:
y = x.reshape(*x.shape, 1)

In [111]:
y

array([[[242],
        [273]],

       [[244],
        [286]],

       [[244],
        [286]]])

In [112]:
y.shape

(3, 2, 1)

In [100]:
value_name = "value"
index_names = ['point', 'component']

In [101]:
index = pd.MultiIndex.from_product([range(s)for s in x.shape], names=index_names)
df = pd.Series(x.flatten(), index=index, name=value_name)
df = df.reset_index()
#df.drop(columns="record_id", inplace=True)

In [103]:
df["image_id"] = "b12312312"

In [113]:
y.reshape(3, 2)

array([[242, 273],
       [244, 286],
       [244, 286]])

In [104]:
df

   point  component  value   image_id
0      0          0    242  b12312312
1      0          1    273  b12312312
2      1          0    244  b12312312
3      1          1    286  b12312312
4      2          0    244  b12312312
5      2          1    286  b12312312

In [38]:
pd.DataFrame(y, columns=["landmark_index", "landmark_coord", "landmark_value"])

ValueError: Must pass 2-d input

In [114]:
from thickshake.storage import Store

In [115]:
store = Store()

In [120]:
store.get_dataframe("/faces/embeddings")

     point  component     value    image_id box_number
0        0          0 -0.017502  b3015271_5          0
1        0          1  0.042054  b3015271_5          0
2        0          2  0.011916  b3015271_5          0
3        0          3  0.080320  b3015271_5          0
4        0          4 -0.131815  b3015271_5          0
5        0          5  0.031043  b3015271_5          0
6        0          6 -0.016294  b3015271_5          0
7        0          7 -0.067521  b3015271_5          0
8        0          8  0.055354  b3015271_5          0
9        0          9 -0.055125  b3015271_5          0
10       0         10  0.199958  b3015271_5          0
11       0         11 -0.033941  b3015271_5          0
12       0         12 -0.198232  b3015271_5          0
13       0         13 -0.073535  b3015271_5          0
14       0         14 -0.044827  b3015271_5          0
15       0         15  0.124208  b3015271_5          0
16       0         16 -0.150590  b3015271_5          0
17       0         17 -0.026711  b3015271_5          0
18       0         18 -0.121676  b3015271_5          0
19       0         19 -0.061474  b3015271_5          0
20       0         20  0.001497  b3015271_5          0
21       0         21  0.024714  b3015271_5          0
22       0         22  0.042444  b3015271_5          0
23       0         23 -0.017252  b3015271_5          0
24       0         24 -0.137206  b3015271_5          0
25       0         25 -0.267679  b3015271_5          0
26       0         26 -0.046300  b3015271_5          0
27       0         27 -0.078298  b3015271_5          0
28       0         28  0.071164  b3015271_5          0
29       0         29 -0.126880  b3015271_5          0
..     ...        ...       ...         ...        ...
98       0         98 -0.213152  b3096711_3          1
99       0         99 -0.004398  b3096711_3          1
100      0        100  0.024775  b3096711_3          1
101      0        101 -0.138874  b3096711_3          1
102      0        102 -0.107475  b3096711_3          1
103      0        103  0.099041  b3096711_3          1
104      0        104 -0.088279  b3096711_3          1
105      0        105  0.166000  b3096711_3          1
106      0        106 -0.044434  b3096711_3          1
107      0        107  0.002738  b3096711_3          1
108      0        108 -0.041470  b3096711_3          1
109      0        109 -0.079993  b3096711_3          1
110      0        110 -0.069828  b3096711_3          1
111      0        111  0.051068  b3096711_3          1
112      0        112  0.192648  b3096711_3          1
113      0        113 -0.257076  b3096711_3          1
114      0        114  0.154623  b3096711_3          1
115      0        115  0.076386  b3096711_3          1
116      0        116  0.017080  b3096711_3          1
117      0        117  0.152333  b3096711_3          1
118      0        118  0.028717  b3096711_3          1
119      0        119  0.001483  b3096711_3          1
120      0        120 -0.050996  b3096711_3          1
121      0        121 -0.143017  b3096711_3          1
122      0        122 -0.193877  b3096711_3          1
123      0        123 -0.156427  b3096711_3          1
124      0        124  0.069745  b3096711_3          1
125      0        125 -0.043333  b3096711_3          1
126      0        126 -0.008536  b3096711_3          1
127      0        127  0.053707  b3096711_3          1

[640 rows x 5 columns]